[versions]
kotlin = "1.9.22"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ktlint = { id = "org.jmailen.kotlinter", version = "3.16.0" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }

[libraries]
# kotlin
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-jackson = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }

# orm
hibernate = { module = "org.hibernate:hibernate-core", version = "6.4.4.Final" }

# aop
aop = { module = "org.springframework.boot:spring-boot-starter-aop" }

# log
slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.9" }

# test
junit = { module = "org.junit.jupiter:junit-jupiter", version = "5.10.0" }
kotest = { module = "io.kotest:kotest-runner-junit5", version = "5.8.0" }
mockk = { module = "io.mockk:mockk", version = "1.13.8" }
